ALTER TABLE STUDENT_PROFILE_REQUEST_DOCUMENT
    DROP CONSTRAINT STUDENT_PROFILE_REQUEST_DOCUMENT_STUDENT_PROFILE_REQUEST_ID_FK;

ALTER TABLE STUDENT_PROFILE_REQUEST_DOCUMENT
    MODIFY (STUDENT_PROFILE_REQUEST_ID NULL);