--Modify EVENT_PAYLOAD Column to BLOB
ALTER TABLE STUDENT_PROFILE_REQUEST_EVENT
    ADD (
        EVENT_PAYLOAD_BLOB BLOB
        ) LOB (EVENT_PAYLOAD_BLOB) STORE AS EVENT_PAYLOAD_BLOB (TABLESPACE API_STUDPROFRQST_BLOB_DATA);
UPDATE STUDENT_PROFILE_REQUEST_EVENT SET EVENT_PAYLOAD_BLOB = UTL_RAW.CAST_TO_RAW(EVENT_PAYLOAD);
ALTER TABLE STUDENT_PROFILE_REQUEST_EVENT DROP COLUMN EVENT_PAYLOAD;
ALTER TABLE STUDENT_PROFILE_REQUEST_EVENT RENAME COLUMN EVENT_PAYLOAD_BLOB TO EVENT_PAYLOAD;
ALTER TABLE STUDENT_PROFILE_REQUEST_EVENT
    MODIFY (
        EVENT_PAYLOAD NOT NULL
        );
