---
apiVersion: v1
kind: Template
labels:
  template: 'student-profile-api-template'
metadata:
  name: 'student-profile-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: pen-demographics-api-pipeline
      name: pen-demographics-api-pipeline
      namespace: c2mvws-tools
    spec:
      source:
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-STUDENT-PROFILE-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/Jenkins/Jenkinsfile
