---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: 'student-profile-api-template'
metadata:
  name: 'student-profile-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: student-profile-api-pipeline
      name: student-profile-api-pipeline
    spec:
      source:
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-STUDENT-PROFILE-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/jenkins/Jenkinsfile
